/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_air.panel.reservation;

import java_air.main.Customer;
import java_air.main.Global;

/**
 *
 * @author Rui Zhang
 */
public class ReservationBillInformDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReservationBillInformDetailPanel
     */
    public ReservationBillInformDetailPanel() {
        initComponents();
        rewardPointsPanel.setVisible(false);
        
    }
    public void setRewardPointsPanel(){
        this.currentPointsLabel.setText(
                String.valueOf(Global.currentCustomer.getCurrentRewardPoints()));
        rewardPointsPanel.setVisible(true);
    }
    
    public void loadCustomerAddress(){
        Customer c = Global.currentCustomer;
        this.firstNameText.setText(c.getFirstName());
        this.billFirstNameText.setText(c.getFirstName());
        this.lastNameText.setText(c.getLastName());
        this.billLastNameText1.setText(c.getLastName());
        this.billAddressText.setText(c.getPhysicalAddress());
        this.billCityText.setText(c.getAddressCity());
        this.billStateText.setText(c.getAddressState());
        this.billZipText.setText(c.getAddressZipCode());
        this.billCountryText.setText("USA");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        travelerLabel = new javax.swing.JLabel();
        paymentLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        connectLabel1 = new javax.swing.JLabel();
        connectLabel2 = new javax.swing.JLabel();
        paymentMethodPanel = new javax.swing.JPanel();
        paymentMethodTitleLabel = new java.awt.Label();
        firstNameLabel = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        cardNumberLabel = new javax.swing.JLabel();
        cardNumberText = new javax.swing.JTextField();
        expireDateLabel = new javax.swing.JLabel();
        expireMonthText = new javax.swing.JTextField();
        expireYearText = new javax.swing.JTextField();
        cvcLabel = new javax.swing.JLabel();
        cvcText = new javax.swing.JTextField();
        billAddressPanel = new javax.swing.JPanel();
        paymentMethodTitleLabel1 = new java.awt.Label();
        billFirstNameLabel = new javax.swing.JLabel();
        billCityText = new javax.swing.JTextField();
        billLastNameLabel = new javax.swing.JLabel();
        billLastNameText1 = new javax.swing.JTextField();
        billAddressLabel = new javax.swing.JLabel();
        billAddressText = new javax.swing.JTextField();
        billStateLabel = new javax.swing.JLabel();
        billFirstNameText = new javax.swing.JTextField();
        billCityLabel = new javax.swing.JLabel();
        billStateText = new javax.swing.JTextField();
        billZipLabel = new javax.swing.JLabel();
        billZipText = new javax.swing.JTextField();
        billCountryLabel = new javax.swing.JLabel();
        billCountryText = new javax.swing.JTextField();
        rewardPointsPanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentPointsLabel = new javax.swing.JLabel();
        useAllPointBox = new javax.swing.JCheckBox();
        useSomePointBox = new javax.swing.JCheckBox();
        rewardPointUseText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(Global.transparentColor);

        jButton1.setBackground(new java.awt.Color(204, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        travelerLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        travelerLabel.setText("Traveler");

        paymentLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        paymentLabel.setText("Payment");

        confirmLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        confirmLabel.setText("Confirm");

        connectLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        connectLabel1.setText("---------");

        connectLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        connectLabel2.setText("----------");

        paymentMethodTitleLabel.setBackground(new java.awt.Color(204, 153, 0));
        paymentMethodTitleLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paymentMethodTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentMethodTitleLabel.setText("Payment");

        firstNameLabel.setFont(Global.normalFont);
        firstNameLabel.setText("First name");

        firstNameText.setFont(Global.normalFont);
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(Global.normalFont);
        lastNameLabel.setText("Last name");

        lastNameText.setFont(Global.normalFont);
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        cardNumberLabel.setFont(Global.normalFont);
        cardNumberLabel.setText("Card number");

        cardNumberText.setFont(Global.normalFont);

        expireDateLabel.setFont(Global.normalFont);
        expireDateLabel.setText("Expire date");

        expireMonthText.setFont(Global.normalFont);

        expireYearText.setFont(Global.normalFont);

        cvcLabel.setFont(Global.normalFont);
        cvcLabel.setText("CVC");

        cvcText.setFont(Global.normalFont);

        javax.swing.GroupLayout paymentMethodPanelLayout = new javax.swing.GroupLayout(paymentMethodPanel);
        paymentMethodPanel.setLayout(paymentMethodPanelLayout);
        paymentMethodPanelLayout.setHorizontalGroup(
            paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentMethodTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paymentMethodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(expireDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paymentMethodPanelLayout.createSequentialGroup()
                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cardNumberText)
                    .addGroup(paymentMethodPanelLayout.createSequentialGroup()
                        .addComponent(expireMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expireYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(cvcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvcText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paymentMethodPanelLayout.setVerticalGroup(
            paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentMethodPanelLayout.createSequentialGroup()
                .addComponent(paymentMethodTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberLabel)
                    .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(paymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expireDateLabel)
                    .addComponent(expireMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expireYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvcLabel)
                    .addComponent(cvcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paymentMethodTitleLabel1.setBackground(new java.awt.Color(204, 153, 0));
        paymentMethodTitleLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paymentMethodTitleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        paymentMethodTitleLabel1.setText("Billing Address");

        billFirstNameLabel.setFont(Global.normalFont);
        billFirstNameLabel.setText("First name");

        billCityText.setFont(Global.normalFont);
        billCityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billCityTextActionPerformed(evt);
            }
        });

        billLastNameLabel.setFont(Global.normalFont);
        billLastNameLabel.setText("Last name");

        billLastNameText1.setFont(Global.normalFont);
        billLastNameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billLastNameText1ActionPerformed(evt);
            }
        });

        billAddressLabel.setFont(Global.normalFont);
        billAddressLabel.setText("Street address");

        billAddressText.setFont(Global.normalFont);
        billAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billAddressTextActionPerformed(evt);
            }
        });

        billStateLabel.setFont(Global.normalFont);
        billStateLabel.setText("State/Province");

        billFirstNameText.setFont(Global.normalFont);
        billFirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billFirstNameTextActionPerformed(evt);
            }
        });

        billCityLabel.setFont(Global.normalFont);
        billCityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        billCityLabel.setText("City");

        billStateText.setFont(Global.normalFont);
        billStateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billStateTextActionPerformed(evt);
            }
        });

        billZipLabel.setFont(Global.normalFont);
        billZipLabel.setText("Postal Code");

        billZipText.setFont(Global.normalFont);
        billZipText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billZipTextActionPerformed(evt);
            }
        });

        billCountryLabel.setFont(Global.normalFont);
        billCountryLabel.setText("Country");

        billCountryText.setFont(Global.normalFont);
        billCountryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billCountryTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout billAddressPanelLayout = new javax.swing.GroupLayout(billAddressPanel);
        billAddressPanel.setLayout(billAddressPanelLayout);
        billAddressPanelLayout.setHorizontalGroup(
            billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentMethodTitleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(billAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billAddressPanelLayout.createSequentialGroup()
                        .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billAddressPanelLayout.createSequentialGroup()
                                .addComponent(billFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(billLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(billLastNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(billAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(billAddressPanelLayout.createSequentialGroup()
                        .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billAddressPanelLayout.createSequentialGroup()
                                .addComponent(billCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(billCountryText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billAddressPanelLayout.createSequentialGroup()
                                .addComponent(billCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(billCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billZipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(billZipText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billStateText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        billAddressPanelLayout.setVerticalGroup(
            billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billAddressPanelLayout.createSequentialGroup()
                .addComponent(paymentMethodTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billLastNameLabel)
                    .addComponent(billLastNameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billStateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billCountryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billZipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billZipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label1.setBackground(new java.awt.Color(204, 153, 0));
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Reward Points");

        jLabel1.setFont(Global.normalFont);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You have Reward Points:");

        jLabel2.setFont(Global.normalFont);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Would you like to redeem?");

        currentPointsLabel.setFont(Global.normalFont);
        currentPointsLabel.setForeground(new java.awt.Color(0, 102, 204));
        currentPointsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentPointsLabel.setText("1354134");

        useAllPointBox.setFont(Global.normalFont);
        useAllPointBox.setText("Yes, I will use all points");
        useAllPointBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                useAllPointBoxStateChanged(evt);
            }
        });
        useAllPointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useAllPointBoxActionPerformed(evt);
            }
        });

        useSomePointBox.setFont(Global.normalFont);
        useSomePointBox.setText("I'd like to use some points");
        useSomePointBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                useSomePointBoxStateChanged(evt);
            }
        });
        useSomePointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSomePointBoxActionPerformed(evt);
            }
        });

        rewardPointUseText.setFont(Global.normalFont);
        rewardPointUseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rewardPointUseTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rewardPointsPanelLayout = new javax.swing.GroupLayout(rewardPointsPanel);
        rewardPointsPanel.setLayout(rewardPointsPanelLayout);
        rewardPointsPanelLayout.setHorizontalGroup(
            rewardPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(currentPointsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rewardPointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(rewardPointsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rewardPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rewardPointsPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rewardPointUseText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(useSomePointBox)
                    .addComponent(useAllPointBox))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        rewardPointsPanelLayout.setVerticalGroup(
            rewardPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rewardPointsPanelLayout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(currentPointsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(useAllPointBox)
                .addGap(8, 8, 8)
                .addComponent(useSomePointBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rewardPointUseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(billAddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentMethodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(rewardPointsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(travelerLabel)
                        .addGap(2, 2, 2)
                        .addComponent(connectLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentLabel)
                        .addGap(4, 4, 4)
                        .addComponent(connectLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectLabel1)
                    .addComponent(connectLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paymentMethodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(billAddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rewardPointsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void billCityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billCityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billCityTextActionPerformed

    private void billLastNameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billLastNameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billLastNameText1ActionPerformed

    private void billAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billAddressTextActionPerformed

    private void billFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billFirstNameTextActionPerformed

    private void billStateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billStateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billStateTextActionPerformed

    private void billZipTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billZipTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billZipTextActionPerformed

    private void billCountryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billCountryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billCountryTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        setPaymentInfor2Reservation();
        ReservationConfirmationPanel reservationConfirmationPanel
                = (ReservationConfirmationPanel) Global.jPanelMap.get(Global.textReservationConfirmation);
        reservationConfirmationPanel.getReservationConfirmDetailPanel().setFlightInformation();
        
        reservationConfirmationPanel.getReservationConfirmDetailPanel().setPaymentInformation();
        Global.panelSwitch(Global.textReservationConfirmation);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void setPaymentInfor2Reservation(){
        Global.currentReservation.setPaymentFirstName(firstNameText.getText());
        Global.currentReservation.setPaymentLastName(lastNameText.getText());
        Global.currentReservation.setPaymentCardNumber(cardNumberText.getText());
    }
    private void useSomePointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSomePointBoxActionPerformed
        useAllPointBox.setSelected(false);
        rewardPointUseText.setVisible(true);
    }//GEN-LAST:event_useSomePointBoxActionPerformed

    private void rewardPointUseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rewardPointUseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rewardPointUseTextActionPerformed

    private void useAllPointBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_useAllPointBoxStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_useAllPointBoxStateChanged

    private void useSomePointBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_useSomePointBoxStateChanged
        // TODO add your handling code here:
        //rewardPointUseText.setVisible(true);
    }//GEN-LAST:event_useSomePointBoxStateChanged

    private void useAllPointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useAllPointBoxActionPerformed
        useSomePointBox.setSelected(false);
        rewardPointUseText.setVisible(false);
    }//GEN-LAST:event_useAllPointBoxActionPerformed
    
    
    
    //private javax.swing.DefaultComboBoxModel monthList
    //        = new javax.swing.DefaultComboBoxModel<>(
    //                new String[] { "1","2","3","4","5","6","7","8","9","10","11","12" });
    private int rewardPointUse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billAddressLabel;
    private javax.swing.JPanel billAddressPanel;
    private javax.swing.JTextField billAddressText;
    private javax.swing.JLabel billCityLabel;
    private javax.swing.JTextField billCityText;
    private javax.swing.JLabel billCountryLabel;
    private javax.swing.JTextField billCountryText;
    private javax.swing.JLabel billFirstNameLabel;
    private javax.swing.JTextField billFirstNameText;
    private javax.swing.JLabel billLastNameLabel;
    private javax.swing.JTextField billLastNameText1;
    private javax.swing.JLabel billStateLabel;
    private javax.swing.JTextField billStateText;
    private javax.swing.JLabel billZipLabel;
    private javax.swing.JTextField billZipText;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JTextField cardNumberText;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JLabel connectLabel1;
    private javax.swing.JLabel connectLabel2;
    private javax.swing.JLabel currentPointsLabel;
    private javax.swing.JLabel cvcLabel;
    private javax.swing.JTextField cvcText;
    private javax.swing.JLabel expireDateLabel;
    private javax.swing.JTextField expireMonthText;
    private javax.swing.JTextField expireYearText;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JPanel paymentMethodPanel;
    private java.awt.Label paymentMethodTitleLabel;
    private java.awt.Label paymentMethodTitleLabel1;
    private javax.swing.JTextField rewardPointUseText;
    private javax.swing.JPanel rewardPointsPanel;
    private javax.swing.JLabel travelerLabel;
    private javax.swing.JCheckBox useAllPointBox;
    private javax.swing.JCheckBox useSomePointBox;
    // End of variables declaration//GEN-END:variables
}
