/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_air.panel.reservation;

import java.awt.Dimension;
import java.util.ArrayList;
import java_air.main.Global;
import java_air.main.Passenger;
import javax.swing.JPanel;

/**
 *
 * @author Georege
 */
public class ReservationPassengerDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReservationPassengerDetailPanel
     */
    public ReservationPassengerDetailPanel() {
        Dimension d = this.getPreferredSize();
        initComponents();
        jScrollPane1.setOpaque(false);
        // increase the scroll bar speed
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(5);
        //travelerLabelSet();
        validate();
        //Dimension d = this.getPreferredSize();
        //d = new Dimension(d.width, d.height+100);
        this.setPreferredSize(d);
    }
    public void travelerLabelSet(){
        rowNumber = Global.currentReservation.getNumberOfPassenger();
        reservationPassengerList = new ArrayList<ReservationSinglePassengerPanel>();
        
        for(int i = 0; i < rowNumber; i++){
            ReservationSinglePassengerPanel reservationSinglePassenger
                    = new ReservationSinglePassengerPanel();
            contentPanel.add(reservationSinglePassenger);
            reservationPassengerList.add(reservationSinglePassenger);
            
            String travelNumberText;
            if(i!=0){
                travelNumberText= "Traveler " + (i+1);
            }else{
                travelNumberText= "Traveler " + (i+1) + " - primary traveler"; 
            }
            
            reservationSinglePassenger.getTravelerLabel().setText(travelNumberText);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        continueButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insideScrollPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();

        setBackground(Global.transparentColor);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Traveler");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("---------");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Payment");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("----------");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Confirm");

        continueButton.setBackground(new java.awt.Color(204, 153, 0));
        continueButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        insideScrollPanel.setBackground(Global.transparentColor);
        insideScrollPanel.setLayout(new java.awt.BorderLayout());

        contentPanel.setLayout(new java.awt.GridLayout(rowNumber, 1, 3, 5));
        insideScrollPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(insideScrollPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continueButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 222, Short.MAX_VALUE)
                        .addComponent(continueButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public JPanel getContentPanel(){
        return contentPanel;
    }
        
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
        Global.panelSwitch(Global.textReservationBillInformation);
    }//GEN-LAST:event_continueButtonActionPerformed
    private int rowNumber = 4;
    private ArrayList<ReservationSinglePassengerPanel> reservationPassengerList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel insideScrollPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
