/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_air.panel.reservation;

import java.awt.Font;
import java_air.main.Passenger;

/**
 *
 * @author Georege
 */
public class ResevationSinglePassengerConfirmPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResevationSinglePassengerConfirmPanel
     */
    public ResevationSinglePassengerConfirmPanel(Passenger p) {
        initComponents();
        
        this.labelFirstNameContent.setText(p.getFirstName());
        this.labelLastNameContent.setText(p.getLastName());
        this.labelDobContent.setText(p.getDateOfBirth());
        this.labelEmailContent.setText(p.getFirstName()+p.getLastName()+"@javaair.com");
        this.labelPhoneContent.setText(p.getPhone());
        this.labelGender.setText(p.getGender());
        this.labelPassportIdContent.setText(p.getPassID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFirstNameContent = new javax.swing.JLabel();
        labelLastNameContent = new javax.swing.JLabel();
        labelDobContent = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelPhoneContent = new javax.swing.JLabel();
        labelPassportIdContent = new javax.swing.JLabel();
        labelPassportId = new javax.swing.JLabel();
        mobileNumberLabel = new javax.swing.JLabel();
        labelEmailContent = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelGenderContent = new javax.swing.JLabel();
        labelDob = new javax.swing.JLabel();

        labelFirstNameContent.setFont(generalFont);
        labelFirstNameContent.setText("First Name,");

        labelLastNameContent.setFont(generalFont);
        labelLastNameContent.setText("Last name");

        labelDobContent.setFont(generalFont);
        labelDobContent.setText("09/08/1980");

        labelGender.setFont(generalFont);
        labelGender.setForeground(new java.awt.Color(102, 102, 102));
        labelGender.setText("Gender:");

        labelPhoneContent.setFont(generalFont);
        labelPhoneContent.setText("219-548-6814");

        labelPassportIdContent.setFont(generalFont);
        labelPassportIdContent.setText("777700757");

        labelPassportId.setFont(generalFont);
        labelPassportId.setForeground(new java.awt.Color(102, 102, 102));
        labelPassportId.setText("Pass ID:");

        mobileNumberLabel.setFont(generalFont);
        mobileNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        mobileNumberLabel.setText("Mobile Number:");

        labelEmailContent.setFont(generalFont);
        labelEmailContent.setText("demo@gmail.com");

        labelEmail.setFont(generalFont);
        labelEmail.setForeground(new java.awt.Color(102, 102, 102));
        labelEmail.setText("Email Address:");

        labelGenderContent.setFont(generalFont);
        labelGenderContent.setText("Male");

        labelDob.setFont(generalFont);
        labelDob.setForeground(new java.awt.Color(102, 102, 102));
        labelDob.setText("Birth Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mobileNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPhoneContent, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelGenderContent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFirstNameContent, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLastNameContent, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPassportId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPassportIdContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelEmailContent, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDob, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelDobContent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 104, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstNameContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastNameContent)
                    .addComponent(labelPassportId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassportIdContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDobContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDob, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelGenderContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPhoneContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmailContent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
private Font generalFont = new java.awt.Font("Times", 0, 18);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDob;
    private javax.swing.JLabel labelDobContent;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmailContent;
    private javax.swing.JLabel labelFirstNameContent;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelGenderContent;
    private javax.swing.JLabel labelLastNameContent;
    private javax.swing.JLabel labelPassportId;
    private javax.swing.JLabel labelPassportIdContent;
    private javax.swing.JLabel labelPhoneContent;
    private javax.swing.JLabel mobileNumberLabel;
    // End of variables declaration//GEN-END:variables
}
