/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_air.panel.reservation;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Georege
 */
public class ReservationPassengerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReservationPassengerPanel
     */
    public ReservationPassengerPanel() {
        initComponents();
        reservationPassengerDetailPanel = new ReservationPassengerDetailPanel();
        reservationPanel1.getContentPanel().add(reservationPassengerDetailPanel,BorderLayout.CENTER);
    }
    public ReservationPanel getReservationPanel(){
        return reservationPanel1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservationPanel1 = new java_air.panel.reservation.ReservationPanel();

        setLayout(new java.awt.BorderLayout());
        add(reservationPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    public ReservationPassengerDetailPanel getReservPassengerDetailPanel(){
        return reservationPassengerDetailPanel;
    }
    private ReservationPassengerDetailPanel reservationPassengerDetailPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java_air.panel.reservation.ReservationPanel reservationPanel1;
    // End of variables declaration//GEN-END:variables
}
