/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_air.panel.reservation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java_air.main.Flight;
import java_air.main.Global;
import java_air.main.Passenger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rui
 */
public class ReservationConfirmDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReservationConfirmDetailPanel
     */
    public ReservationConfirmDetailPanel() {
        Dimension d = this.getPreferredSize();
        initComponents();
        //travelerLabelSet();
        validate();
        this.setPreferredSize(d);
    }//end constructor
    
    public void setPassengerLabels(){
        //for(int i = 0; i < Global.currentReservation.getNumberOfPassenger(); i++){
        for(Passenger p : Global.currentReservation.getPassengerList()){
            ResevationSinglePassengerConfirmPanel reservationSingleConfirmPassenger
                    = new ResevationSinglePassengerConfirmPanel(p);
            travelerContentPanel.add(reservationSingleConfirmPassenger);
        }//end for loop 
    }//end travelerLabelSet()
    
    //private Reservation reservation = Global.currentReservation;
    public void setFlightInformation(){
        Reservation reservation = Global.currentReservation;
        Flight orginFlight = Global.currentReservation.getOriginFlight();
        Flight returnFlight;
        orginFlightAirport.setText(orginFlight.getOriginAirport()+ " - " + orginFlight.getDestinationAirport());
        orginFlightDateLabel.setText(reservation.getFlightOriginDatePrint());
        orginFlightTimeLabel.setText(orginFlight.getScheduledDeparture() + " - "
                                        + orginFlight.getScheduledArrival());
        orginFlightPassengerLabel.setText(reservation.getNumberOfPassenger() + " traveler");
        if(reservation.getIsRoundTrip()){
          LabelsShow(true);
          returnFlight = reservation.getReturnFlight();
          returnFlightAirport.setText(returnFlight.getOriginAirport()+ " - " + returnFlight.getDestinationAirport());
          returnFlightDateLabel.setText(reservation.getFlightReturnDatePrint());
          returnFTimeLabel.setText(returnFlight.getScheduledDeparture() + " - "
                                        + returnFlight.getScheduledArrival());
          returnFlightPassengerLabel.setText(reservation.getNumberOfPassenger() + " traveler");
        }else{
            LabelsShow(false);        
        }//end if-else
    }//end setFlightInformation()
    
    private void LabelsShow(Boolean booleanValue) {
           returnFlightAirport.setVisible(booleanValue);
           returnFlightDateLabel.setVisible(booleanValue);
           returnFTimeLabel.setVisible(booleanValue);
           returnFlightPassengerLabel.setVisible(booleanValue);      
           outBoundLabel.setVisible(booleanValue);  
           returnLabel.setVisible(booleanValue);  
    }//end LabelsShow()
    
    public void setPaymentInformation(){
        Reservation reservation = Global.currentReservation;
        firstNameInforLabel.setText(reservation.getPaymentFirstName());
        lastNameInforLabel1.setText(reservation.getPaymentLastName());
        cardNumberInforLabel.setText(reservation.getPaymentCardNumber());
        
        PriceCalculator priceCalculator = Global.currentReservation.getPriceCalcuator();
        this.fareFeeLabel.setText(priceCalculator.getFare());
        this.taxFeeLabel.setText(priceCalculator.getTaxFee());
        this.totalPriceLabel.setText(priceCalculator.getTotalFee());
        
        if(Global.currentCustomer != null){
            this.rewardLabel.setVisible(true);
            this.rewardInforLabel.setVisible(true);
            this.rewardInforLabel.setText("(" + priceCalculator.getRewardRedeem() + ")");
            //this.rewardLabel.setText(priceCalculator.getRewardRedeem());
            this.rewardLabel.setText(priceCalculator.getRewardPointsUsed());
        }else{
            this.rewardLabel.setVisible(false);
            this.rewardInforLabel.setVisible(false);
        }//end if-else
    }//end setPaymentInformation()
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confirmReservationButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insideSrollPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        orginFlightPassengerLabel = new javax.swing.JLabel();
        orginFlightDateLabel = new javax.swing.JLabel();
        orginFlightAirport = new javax.swing.JLabel();
        orginFlightTimeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PassengerTitleLabel = new java.awt.Label();
        firstNameInforLabel = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel1 = new javax.swing.JLabel();
        lastNameInforLabel1 = new javax.swing.JLabel();
        cardNumberInforLabel = new javax.swing.JLabel();
        paymentMethodTitleLabel1 = new java.awt.Label();
        jSeparator2 = new javax.swing.JSeparator();
        travelerContentPanel = new javax.swing.JPanel();
        fareLabel1 = new javax.swing.JLabel();
        fareFeeLabel = new javax.swing.JLabel();
        taxLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        taxFeeLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        rewardLabel = new javax.swing.JLabel();
        rewardInforLabel = new javax.swing.JLabel();
        returnFlightAirport = new javax.swing.JLabel();
        returnFlightPassengerLabel = new javax.swing.JLabel();
        returnFlightDateLabel = new javax.swing.JLabel();
        returnFTimeLabel = new javax.swing.JLabel();
        outBoundLabel = new javax.swing.JLabel();
        returnLabel = new javax.swing.JLabel();

        setBackground(Global.transparentColor);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Traveler");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("---------");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Payment");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("----------");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Confirm");

        confirmReservationButton.setBackground(new java.awt.Color(204, 153, 0));
        confirmReservationButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        confirmReservationButton.setText("Confirm");
        confirmReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmReservationButtonActionPerformed(evt);
            }
        });

        insideSrollPanel.setLayout(new java.awt.BorderLayout());

        label1.setBackground(new java.awt.Color(204, 153, 0));
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Flight");

        orginFlightPassengerLabel.setFont(generalFont);
        orginFlightPassengerLabel.setText("4 traveler");

        orginFlightDateLabel.setFont(generalFont);
        orginFlightDateLabel.setForeground(generalColor);
        orginFlightDateLabel.setText("Tue, Nov 23, 2016");

        orginFlightAirport.setFont(generalFont);
        orginFlightAirport.setForeground(generalColor);
        orginFlightAirport.setText("Chicago - NewYork");

        orginFlightTimeLabel.setFont(generalFont);
        orginFlightTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        orginFlightTimeLabel.setText("6:00 am - 9:07 am");

        PassengerTitleLabel.setBackground(new java.awt.Color(204, 153, 0));
        PassengerTitleLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PassengerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        PassengerTitleLabel.setText("Traveler");

        firstNameInforLabel.setFont(generalFont);
        firstNameInforLabel.setText("First name");

        cardNumberLabel.setFont(generalFont);
        cardNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        cardNumberLabel.setText("Card number");

        lastNameLabel.setFont(generalFont);
        lastNameLabel.setForeground(new java.awt.Color(102, 102, 102));
        lastNameLabel.setText("Last name");

        firstNameLabel1.setFont(generalFont);
        firstNameLabel1.setForeground(new java.awt.Color(102, 102, 102));
        firstNameLabel1.setText("First name");

        lastNameInforLabel1.setFont(generalFont);
        lastNameInforLabel1.setText("Last name");

        cardNumberInforLabel.setFont(generalFont);
        cardNumberInforLabel.setText("**********5487");

        paymentMethodTitleLabel1.setBackground(new java.awt.Color(204, 153, 0));
        paymentMethodTitleLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        paymentMethodTitleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        paymentMethodTitleLabel1.setText("Payment");

        travelerContentPanel.setLayout(new java.awt.GridLayout(rowNumber, 1));

        fareLabel1.setFont(generalFont);
        fareLabel1.setForeground(new java.awt.Color(102, 102, 102));
        fareLabel1.setText("Fare");

        fareFeeLabel.setFont(generalFont);
        fareFeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fareFeeLabel.setText("$500,00");

        taxLabel1.setFont(generalFont);
        taxLabel1.setForeground(new java.awt.Color(102, 102, 102));
        taxLabel1.setText("Taxes and fees");

        jLabel8.setFont(generalFont);
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Total");

        taxFeeLabel.setFont(generalFont);
        taxFeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taxFeeLabel.setText("$28.33");

        totalPriceLabel.setFont(generalFont);
        totalPriceLabel.setForeground(generalColor);
        totalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPriceLabel.setText("$508.33");

        rewardLabel.setFont(generalFont);
        rewardLabel.setForeground(new java.awt.Color(102, 102, 102));
        rewardLabel.setText("Rewards redeem");

        rewardInforLabel.setFont(generalFont);
        rewardInforLabel.setForeground(generalColor);
        rewardInforLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rewardInforLabel.setText("-$20.33");

        returnFlightAirport.setFont(generalFont);
        returnFlightAirport.setForeground(generalColor);
        returnFlightAirport.setText("Chicago - NewYork");

        returnFlightPassengerLabel.setFont(generalFont);
        returnFlightPassengerLabel.setText("4 traveler");

        returnFlightDateLabel.setFont(generalFont);
        returnFlightDateLabel.setForeground(generalColor);
        returnFlightDateLabel.setText("Tue, Nov 23, 2016");

        returnFTimeLabel.setFont(generalFont);
        returnFTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        returnFTimeLabel.setText("6:00 am - 9:07 am");

        outBoundLabel.setFont(Global.normalFont);
        outBoundLabel.setText("Outbound");

        returnLabel.setFont(Global.normalFont);
        returnLabel.setText("Return");

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PassengerTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(travelerContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(firstNameInforLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameInforLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cardNumberInforLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(rewardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rewardInforLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(fareLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fareFeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(taxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(taxFeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ContentPanelLayout.createSequentialGroup()
                                    .addComponent(orginFlightAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(orginFlightPassengerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContentPanelLayout.createSequentialGroup()
                                    .addComponent(orginFlightDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(orginFlightTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(outBoundLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnLabel)
                            .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ContentPanelLayout.createSequentialGroup()
                                    .addComponent(returnFlightAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(returnFlightPassengerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContentPanelLayout.createSequentialGroup()
                                    .addComponent(returnFlightDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(returnFTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paymentMethodTitleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outBoundLabel)
                    .addComponent(returnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orginFlightPassengerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orginFlightAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orginFlightDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orginFlightTimeLabel))
                        .addGap(15, 15, 15))
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnFlightPassengerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnFlightAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnFlightDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnFTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fareFeeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fareLabel1))
                    .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameInforLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameLabel)
                        .addComponent(firstNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameInforLabel1)))
                .addGap(10, 10, 10)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cardNumberLabel)
                        .addComponent(cardNumberInforLabel))
                    .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taxFeeLabel)
                        .addComponent(taxLabel1)))
                .addGap(10, 10, 10)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rewardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rewardInforLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(PassengerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(travelerContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentPanelLayout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(paymentMethodTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(367, Short.MAX_VALUE)))
        );

        insideSrollPanel.add(ContentPanel, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(insideSrollPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(10, 10, 10)
                        .addComponent(confirmReservationButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confirmReservationButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmReservationButtonActionPerformed
        boolean reserveSuccessful = false;
        try{
            reserveSuccessful = Global.currentReservation.saveReservationToDB();
        }
        catch(Exception x){
            JOptionPane.showMessageDialog(null
                ,x.getMessage()
                ,"DB Reservation Save Error"
                ,JOptionPane.ERROR_MESSAGE);
        }
        
        if(reserveSuccessful){
            Global.currentReservation = null;
            Global.panelSwitch(Global.textHome);
        }
    }//GEN-LAST:event_confirmReservationButtonActionPerformed
    private int rowNumber = 4;
    private Font generalFont = new java.awt.Font("Times", 0, 18);
    private Color generalColor = new java.awt.Color(0, 102, 255);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private java.awt.Label PassengerTitleLabel;
    private javax.swing.JLabel cardNumberInforLabel;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JButton confirmReservationButton;
    private javax.swing.JLabel fareFeeLabel;
    private javax.swing.JLabel fareLabel1;
    private javax.swing.JLabel firstNameInforLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JPanel insideSrollPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label1;
    private javax.swing.JLabel lastNameInforLabel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel orginFlightAirport;
    private javax.swing.JLabel orginFlightDateLabel;
    private javax.swing.JLabel orginFlightPassengerLabel;
    private javax.swing.JLabel orginFlightTimeLabel;
    private javax.swing.JLabel outBoundLabel;
    private java.awt.Label paymentMethodTitleLabel1;
    private javax.swing.JLabel returnFTimeLabel;
    private javax.swing.JLabel returnFlightAirport;
    private javax.swing.JLabel returnFlightDateLabel;
    private javax.swing.JLabel returnFlightPassengerLabel;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JLabel rewardInforLabel;
    private javax.swing.JLabel rewardLabel;
    private javax.swing.JLabel taxFeeLabel;
    private javax.swing.JLabel taxLabel1;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JPanel travelerContentPanel;
    // End of variables declaration//GEN-END:variables
}
